import toast from "react-hot-toast";
import { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CartContext } from "../context/CartContext";
import PageTransition from "../components/PageTransition";
import SEO from "../components/SEO";
import "../styles/Checkout.css";

const digits = (v) => v.replace(/\D/g, "");
const maskCPF = (v) => digits(v).slice(0,11).replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2");
const maskPhone = (v) => digits(v).slice(0,11).replace(/(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2");
const maskCEP = (v) => digits(v).slice(0,8).replace(/(\d{5})(\d)/,"$1-$2");
const maskCard = (v) => digits(v).slice(0,16).replace(/(\d{4})(?=\d)/g,"$1 ");
const maskExpiry = (v) => digits(v).slice(0,4).replace(/(\d{2})(\d)/,"$1/$2");

export default function Checkout() {
  const { cart, clearCart } = useContext(CartContext); const navigate = useNavigate();
  const [shipping,setShipping]=useState(0),[discount,setDiscount]=useState(0),[coupon,setCoupon]=useState(""),[payment,setPayment]=useState("pix");
  const [form,setForm]=useState({name:"",email:"",cpf:"",phone:"",cep:"",number:"",address:"",city:"",state:"",card:"",expiry:"",cvv:""});
  const subtotal=cart.reduce((sum,item)=>sum+item.price*(item.quantity||1),0); const total=Math.max(0,subtotal+shipping-discount);
  const change=(key,value)=>setForm(prev=>({...prev,[key]:value}));
  function applyCoupon(){if(coupon.trim().toUpperCase()==="MAVILA10"){setDiscount(subtotal*.1);toast.success("Cupom MAVILA10 aplicado: 10% OFF!");}else{setDiscount(0);toast.error("Cupom inválido.");}}
  function validate(){if(cart.length===0)return "Seu carrinho está vazio.";if(form.name.trim().length<3)return "Preencha seu nome completo.";if(!/^\S+@\S+\.\S+$/.test(form.email))return "Digite um email válido.";if(digits(form.cpf).length!==11)return "Digite um CPF válido.";if(digits(form.phone).length<10)return "Digite um telefone válido.";if(digits(form.cep).length!==8)return "Digite um CEP válido.";if(!form.number||!form.address.trim()||!form.city.trim()||form.state.trim().length<2)return "Complete seu endereço.";if(payment==="card"&&(digits(form.card).length!==16||digits(form.expiry).length!==4||digits(form.cvv).length<3))return "Confira os dados do cartão.";return null;}
  function handleFinishOrder(){const error=validate();if(error){toast.error(error);return;}const orders=JSON.parse(localStorage.getItem("mavila-orders")||"[]");const order={id:`MV${Date.now().toString().slice(-8)}`,date:new Date().toISOString(),items:cart,total,payment,shipping,status:"Pedido confirmado"};localStorage.setItem("mavila-orders",JSON.stringify([order,...orders]));localStorage.setItem("mavila-last-order",JSON.stringify(order));clearCart();navigate("/pedido-confirmado");}
  return <PageTransition><SEO title="Checkout — MAVILA" description="Finalize sua compra MAVILA."/><div className="checkout-page"><section className="checkout-left"><div className="checkout-header"><span>CHECKOUT</span><h1>Finalizar Compra</h1><p>Preencha seus dados para concluir seu pedido.</p></div>
  <div className="checkout-section"><h2>Dados pessoais</h2><div className="form-grid"><div className="form-group full"><label>Nome completo</label><input value={form.name} onChange={e=>change("name",e.target.value)} placeholder="Seu nome completo"/></div><div className="form-group full"><label>Email</label><input type="email" value={form.email} onChange={e=>change("email",e.target.value)} placeholder="seuemail@email.com"/></div><div className="form-group"><label>CPF</label><input value={form.cpf} onChange={e=>change("cpf",maskCPF(e.target.value))} placeholder="000.000.000-00" inputMode="numeric"/></div><div className="form-group"><label>Telefone</label><input value={form.phone} onChange={e=>change("phone",maskPhone(e.target.value))} placeholder="(11) 99999-9999" inputMode="tel"/></div></div></div>
  <div className="checkout-section"><h2>Endereço</h2><div className="form-grid"><div className="form-group"><label>CEP</label><input value={form.cep} onChange={e=>change("cep",maskCEP(e.target.value))} placeholder="00000-000" inputMode="numeric"/></div><div className="form-group"><label>Número</label><input value={form.number} onChange={e=>change("number",e.target.value)} placeholder="123"/></div><div className="form-group full"><label>Endereço</label><input value={form.address} onChange={e=>change("address",e.target.value)} placeholder="Rua, avenida..."/></div><div className="form-group"><label>Cidade</label><input value={form.city} onChange={e=>change("city",e.target.value)} placeholder="Sua cidade"/></div><div className="form-group"><label>Estado</label><input value={form.state} onChange={e=>change("state",e.target.value.toUpperCase().slice(0,2))} placeholder="SP"/></div></div></div>
  <div className="checkout-section"><h2>Entrega</h2><div className="shipping-options"><label className={`option-card ${shipping===0?"selected":""}`}><input type="radio" name="shipping" checked={shipping===0} onChange={()=>setShipping(0)}/><div><strong>Entrega padrão</strong><span>5 a 8 dias úteis</span></div><b>Grátis</b></label><label className={`option-card ${shipping===29.9?"selected":""}`}><input type="radio" name="shipping" checked={shipping===29.9} onChange={()=>setShipping(29.9)}/><div><strong>Entrega expressa</strong><span>1 a 3 dias úteis</span></div><b>R$ 29,90</b></label></div></div>
  <div className="checkout-section"><h2>Pagamento</h2><div className="payment-options"><button type="button" className={payment==="pix"?"selected":""} onClick={()=>setPayment("pix")}>PIX</button><button type="button" className={payment==="card"?"selected":""} onClick={()=>setPayment("card")}>Cartão</button><button type="button" className={payment==="boleto"?"selected":""} onClick={()=>setPayment("boleto")}>Boleto</button></div>{payment==="card"&&<div className="card-fields"><div className="form-group full"><label>Número do cartão</label><input value={form.card} onChange={e=>change("card",maskCard(e.target.value))} placeholder="0000 0000 0000 0000" inputMode="numeric"/></div><div className="form-group"><label>Validade</label><input value={form.expiry} onChange={e=>change("expiry",maskExpiry(e.target.value))} placeholder="MM/AA" inputMode="numeric"/></div><div className="form-group"><label>CVV</label><input value={form.cvv} onChange={e=>change("cvv",digits(e.target.value).slice(0,4))} placeholder="123" inputMode="numeric"/></div></div>}</div></section>
  <aside className="checkout-right"><h2>Resumo do Pedido</h2><div className="checkout-products">{cart.length===0?<p className="checkout-empty">Seu carrinho está vazio.</p>:cart.map((item,index)=><div className="checkout-product" key={`${item.name}-${item.color}-${item.size}-${index}`}><img src={item.image} alt={item.name}/><div className="checkout-product-info"><strong>{item.name}</strong>{item.color&&<span>{item.color}</span>}{item.size&&<span>Tamanho {item.size}</span>}<span>Quantidade: {item.quantity||1}</span></div><strong>R$ {(item.price*(item.quantity||1)).toLocaleString("pt-BR",{minimumFractionDigits:2})}</strong></div>)}</div><div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Cupom: MAVILA10"/><button type="button" onClick={applyCoupon}>Aplicar</button></div><div className="checkout-values"><div><span>Subtotal</span><strong>R$ {subtotal.toLocaleString("pt-BR",{minimumFractionDigits:2})}</strong></div><div><span>Frete</span><strong>{shipping===0?"Grátis":`R$ ${shipping.toLocaleString("pt-BR",{minimumFractionDigits:2})}`}</strong></div>{discount>0&&<div><span>Desconto</span><strong>- R$ {discount.toLocaleString("pt-BR",{minimumFractionDigits:2})}</strong></div>}</div><div className="checkout-total"><span>Total</span><strong>R$ {total.toLocaleString("pt-BR",{minimumFractionDigits:2})}</strong></div><button className="finish-order" type="button" onClick={handleFinishOrder}>Finalizar Pedido</button><p className="secure-checkout">🔒 Checkout demonstrativo — nenhuma cobrança real é realizada.</p></aside></div></PageTransition>;
}
